#ifndef PROFLOG_CONFIG_H
#define PROFLOG_CONFIG_H

#define MAX_LOG_LINE_LEN 128

#define MAX_LOG_DEFINITIONS_COUNT 10

#define MAX_LOG_PARAM_COUNT 4
#define MAX_LOG_PARAM_NAME_LEN 16
#define MAX_LOG_PARAM_STRING_LEN 32

#endif //PROFLOG_CONFIG_H